<Curriculum>:
    BoxLayout:
        MDAccordion:
            orientation: 'horizontal'
            size_hint_x: None
            width: '240dp'
            MDAccordionItem:
                title:'BOOKS'
                icon: 'book-open'
                MDAccordionSubItem:
                    text: "MATHS"
                MDAccordionSubItem:
                    text: "PHYSICS"
                MDAccordionSubItem:
                    text: "CURRICULUM"