<Subject>:
    BoxLayout:
        MDAccordion:
            orientation: 'vertical'
            size_hint_x: None
            width: '240dp'
            MDAccordionItem:
                title:'Subjects'
                icon: 'book-open'
                MDAccordionSubItem:
                    text: "MATHS"
                MDAccordionSubItem:
                    text: "PHYSICS"
                MDAccordionSubItem:
                    text: "CHEMISTRY"